/**
 * Validation for the onboarding wizard.
 *
 * Kept out of the route component so the rules are unit-testable and so the
 * error copy lives in one place. Every message is written to be shown directly
 * to a user — no "invalid input", which tells them nothing about what to fix.
 */
import { z } from "zod";

/** Institution codes are generated by `secrets.token_hex(4).upper()` server-side. */
export const institutionCodeSchema = z
  .string()
  .trim()
  .min(4, "That code looks too short — it should be 8 characters.")
  .max(32, "That code looks too long — check for extra characters.")
  .regex(/^[A-Za-z0-9_-]+$/, "Codes only contain letters, numbers, dashes and underscores.");

export const institutionNameSchema = z
  .string()
  .trim()
  .min(3, "Use your institution's full name (at least 3 characters).")
  .max(200, "That name is too long — keep it under 200 characters.");

export const departmentSchema = z
  .string()
  .trim()
  .min(2, "Enter the department you teach in.")
  .max(100, "That department name is too long.");

/**
 * Comma-separated subject list. Empty is allowed — a faculty member may examine
 * across subjects and shouldn't be blocked at a wizard step over it.
 */
export const subjectsSchema = z
  .string()
  .max(500, "That's a lot of subjects — keep the list under 500 characters.");

/** Split a comma-separated list into clean values, dropping blanks and dupes. */
export function parseSubjects(raw: string): string[] {
  const seen = new Set<string>();
  for (const part of raw.split(",")) {
    const value = part.trim();
    if (value) seen.add(value);
  }
  return [...seen];
}

export type StepName =
  | "institution"
  | "academics"
  | "project"
  | "goals"
  | "teaching"
  | "institution_create"
  | "invite_faculty";

export interface StepValues {
  institutionCode: string;
  institutionName: string;
  department: string;
  subjects: string;
}

/**
 * Validate one wizard step. Returns an error message to display, or null when
 * the step may be left.
 *
 * `role` matters: an institution code is optional for a student (B2C signup
 * must not be blocked) but required for faculty, because the backend refuses a
 * gated role with no institution to approve it.
 */
export function validateStep(step: StepName, role: string, values: StepValues): string | null {
  switch (step) {
    case "institution": {
      const raw = values.institutionCode.trim();
      if (!raw) {
        return role === "student"
          ? null // students may skip
          : "Your institution's code is required for faculty access. Ask your admin for it.";
      }
      const parsed = institutionCodeSchema.safeParse(raw);
      return parsed.success ? null : (parsed.error.issues[0]?.message ?? "Check that code.");
    }
    case "institution_create": {
      const parsed = institutionNameSchema.safeParse(values.institutionName);
      return parsed.success ? null : (parsed.error.issues[0]?.message ?? "Check that name.");
    }
    case "teaching": {
      const dept = departmentSchema.safeParse(values.department);
      if (!dept.success) return dept.error.issues[0]?.message ?? "Check your department.";
      const subj = subjectsSchema.safeParse(values.subjects);
      return subj.success ? null : (subj.error.issues[0]?.message ?? "Check your subjects.");
    }
    // These steps have defaults selected already, so there is nothing to fail.
    case "academics":
    case "project":
    case "goals":
    case "invite_faculty":
      return null;
  }
}
