"""Terms & Conditions — legal requirements under the IT Act 2000,
Consumer Protection (E-Commerce) Rules 2020, and DPDP Act 2023."""

from fastapi import APIRouter

router = APIRouter(prefix="/api/terms", tags=["terms"])

TERMS_VERSION = "1.0"

# Shaped to satisfy the IT Act §79 intermediary requirements, the Consumer
# Protection (E-Commerce) Rules 2020, and the DPDP Act 2023.  Each section
# maps to a specific legal obligation — the same provenance-driven approach
# the privacy notice uses.
TERMS_AND_CONDITIONS = {
    "version": TERMS_VERSION,
    "last_updated": "2026-08-28",
    "title": "VivAI — Terms and Conditions",
    "governing_law": "Laws of India",
    "jurisdiction": "Courts at Bengaluru, Karnataka, India",
    "entity": {
        "name": "VivAI",
        "description": (
            "An AI-powered student companion platform providing mock viva, "
            "presentation coaching, pitch drill, communication coaching, "
            "project management and collaborative team features."
        ),
        "contact": "support@vivai.app",
    },
    "summary": (
        "These Terms govern your use of VivAI. By creating an account or "
        "using any feature of the platform, you agree to be bound by these "
        "Terms together with our Privacy Notice. If you do not agree, do not "
        "use the platform."
    ),
    "sections": [
        {
            "heading": "1. Eligibility",
            "body": (
                "VivAI is available to individuals who are at least 13 years "
                "of age. Users under 18 must have verifiable consent from a "
                "parent or lawful guardian under the Digital Personal Data "
                "Protection Act, 2023. By using VivAI you represent that you "
                "meet these eligibility requirements and that all information "
                "you provide during registration is accurate."
            ),
        },
        {
            "heading": "2. Account responsibilities",
            "body": (
                "You are responsible for maintaining the confidentiality of "
                "your account credentials and for all activity that occurs "
                "under your account. You must notify us immediately at "
                "support@vivai.app if you suspect unauthorised access. We are "
                "not liable for any loss arising from unauthorised use of your "
                "account."
            ),
        },
        {
            "heading": "3. Acceptable use",
            "body": (
                "You agree not to: (a) use VivAI for any unlawful purpose; "
                "(b) attempt to gain unauthorised access to any part of the "
                "platform or its infrastructure; (c) scrape, crawl or "
                "automatically extract data from the platform; (d) upload "
                "malicious code, viruses or any content that could harm the "
                "platform or other users; (e) impersonate another person or "
                "misrepresent your affiliation; (f) harass, bully or "
                "intimidate other users; (g) use the platform to provide "
                "services to third parties (e.g. taking vivas on behalf of "
                "someone else); or (h) circumvent any usage limits, rate "
                "limits or consent gates. We may suspend or terminate your "
                "account for violations."
            ),
        },
        {
            "heading": "4. Services and AI-generated content",
            "body": (
                "VivAI provides AI-powered practice tools including mock "
                "viva examinations, presentation coaching, pitch drills and "
                "communication coaching. Scores, feedback, model answers and "
                "reports are generated by artificial intelligence (Google "
                "Gemini). AI-generated content is provided for educational "
                "and practice purposes only — it is not a substitute for "
                "professional academic evaluation, career advice or "
                "certification. We do not guarantee the accuracy or "
                "completeness of AI-generated outputs."
            ),
        },
        {
            "heading": "5. Intellectual property",
            "body": (
                "The VivAI platform, including its design, code, branding, "
                "AI prompts, templates, and documentation, is owned by or "
                "licensed to VivAI. You receive a limited, non-exclusive, "
                "non-transferable licence to use the platform for your "
                "personal educational purposes. You retain full ownership of "
                "any project files, source code and original content you "
                "upload. We do not claim any rights over your uploaded "
                "content, and we do not use it to train AI models."
            ),
        },
        {
            "heading": "6. Data processing and privacy",
            "body": (
                "Our collection, use and protection of your personal data is "
                "governed by the VivAI Privacy Notice, which forms part of "
                "these Terms. The Privacy Notice is provided under the "
                "Digital Personal Data Protection Act, 2023 and the DPDP "
                "Rules, 2025. By accepting these Terms you also acknowledge "
                "the Privacy Notice. You may withdraw consent or request "
                "erasure of your data at any time through your profile "
                "settings or by contacting our Grievance Officer."
            ),
        },
        {
            "heading": "7. Institution features",
            "body": (
                "Some features allow institutional access — faculty can "
                "schedule assessed vivas, review cohort performance, and "
                "manage teams. Institutions are responsible for ensuring "
                "they have appropriate authorisation to process student data "
                "through VivAI. Institutional administrators must ensure "
                "that student members are informed of and have consented to "
                "the processing described in the Privacy Notice."
            ),
        },
        {
            "heading": "8. Limitation of liability",
            "body": (
                "To the maximum extent permitted by applicable law, VivAI "
                "shall not be liable for any indirect, incidental, "
                "consequential, special, or punitive damages arising out of "
                "or relating to your use of the platform, including but not "
                "limited to loss of data, loss of academic opportunities, or "
                "reliance on AI-generated scores. Our total aggregate "
                "liability shall not exceed the amount you paid to VivAI in "
                "the twelve (12) months preceding the claim, or ₹500 "
                "(whichever is greater). Nothing in these Terms limits our "
                "liability for deficiency in services under the Consumer "
                "Protection Act, 2019."
            ),
        },
        {
            "heading": "9. Disclaimers",
            "body": (
                "VivAI is provided on an \"as is\" and \"as available\" "
                "basis. We disclaim all warranties, express or implied, "
                "including merchantability, fitness for a particular "
                "purpose, and non-infringement. We do not warrant that the "
                "platform will be uninterrupted, error-free, or free of "
                "harmful components. AI scores and reports are approximate "
                "indications of readiness and should not be treated as "
                "definitive assessments."
            ),
        },
        {
            "heading": "10. Termination",
            "body": (
                "You may delete your account at any time through your "
                "profile settings. We may suspend or terminate your access "
                "if you breach these Terms, if required by law, or if we "
                "discontinue the platform. Upon termination, your right to "
                "use VivAI ceases. Sections 5 (Intellectual Property), 8 "
                "(Limitation of Liability), 9 (Disclaimers), and 11 "
                "(Governing Law) survive termination. You may request "
                "deletion of your data as described in the Privacy Notice."
            ),
        },
        {
            "heading": "11. Governing law and dispute resolution",
            "body": (
                "These Terms are governed by the laws of India. Any dispute "
                "arising out of or relating to these Terms or your use of "
                "VivAI shall be subject to the exclusive jurisdiction of the "
                "courts at Bengaluru, Karnataka, India. Before initiating "
                "legal proceedings you agree to first raise the dispute "
                "with our Grievance Officer and allow a reasonable period "
                "for resolution."
            ),
        },
        {
            "heading": "12. Grievance officer",
            "body": (
                "Under the IT (Intermediary Guidelines and Digital Media "
                "Ethics Code) Rules, 2021 and the DPDP Rules, 2025, we "
                "have appointed a Grievance Officer for India. "
                "Grievance Officer — VivAI\n"
                "Email: grievance@vivai.app\n"
                "Response time: We aim to respond within 7 working days, "
                "and in any case within the 90 days the DPDP Rules 2025 "
                "allow."
            ),
        },
        {
            "heading": "13. Amendments",
            "body": (
                "We may update these Terms from time to time. When we make "
                "material changes we will notify you through the platform "
                "or by email and, where required by law, ask for your "
                "re-acceptance. Your continued use of VivAI after the "
                "notice period constitutes acceptance of the amended Terms. "
                "The current version number and last-updated date are shown "
                "at the top of this page."
            ),
        },
        {
            "heading": "14. Miscellaneous",
            "body": (
                "If any provision of these Terms is found to be "
                "unenforceable, the remaining provisions continue in full "
                "force. Our failure to enforce any right or provision shall "
                "not constitute a waiver of that right or provision. These "
                "Terms, together with the Privacy Notice, constitute the "
                "entire agreement between you and VivAI regarding use of "
                "the platform."
            ),
        },
    ],
}


@router.get("/policy")
def get_terms():
    """Return the current Terms & Conditions (public, no auth required)."""
    return TERMS_AND_CONDITIONS
