"""A traceback's most valuable lines are its LAST ones.

The first report generated by this system truncated stacks from the tail, so
every entry ended in a wall of framework frames with the actual exception line
cut off. That is the one line a reader needs.
"""
from __future__ import annotations

from core.diagnostics import redact as R
from core.diagnostics.handler import MAX_STACK_CHARS, trim_stack


def _huge_traceback() -> str:
    frames = [
        f'  File "C:\\app\\.venv\\Lib\\site-packages\\starlette\\routing.py", line {i}, in app\n'
        f"    await self.app(scope, receive, send)\n"
        for i in range(400)
    ]
    return (
        "Traceback (most recent call last):\n"
        + "".join(frames)
        + '  File "C:\\app\\backend\\api\\live.py", line 447, in finalize\n'
        + "    report = report_service.build_report(...)\n"
        + "ValueError: the actual root cause\n"
    )


def test_a_short_stack_is_left_alone():
    stack = 'Traceback:\n  File "a.py", line 1\nValueError: x\n'
    assert trim_stack(stack) == stack


def test_the_final_exception_line_always_survives():
    trimmed = trim_stack(_huge_traceback())
    assert "ValueError: the actual root cause" in trimmed
    assert "live.py" in trimmed, "the raising app frame must survive"


def test_the_first_frames_survive_too():
    trimmed = trim_stack(_huge_traceback())
    assert trimmed.startswith("Traceback (most recent call last):")


def test_the_middle_is_what_gets_dropped_and_it_says_so():
    trimmed = trim_stack(_huge_traceback())
    assert "intermediate frames omitted" in trimmed
    assert len(trimmed) <= MAX_STACK_CHARS + 200


def test_redaction_does_not_re_clip_a_stack_to_the_short_string_budget():
    """Regression: redact_obj applied the generic 2000-char cap to `stack`,
    undoing the trim and cutting the exception line off again."""
    stack = trim_stack(_huge_traceback())
    out = R.redact_obj({"error": {"stack": stack, "type": "ValueError"}})
    kept = out["error"]["stack"]
    assert "ValueError: the actual root cause" in kept, "the root cause was clipped away"
    assert len(kept) > R.MAX_STRING_CHARS


def test_a_secret_inside_a_stack_is_still_redacted():
    jwt = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.abcdefghijklmnopqrstuvwxyz012345"
    stack = f'Traceback:\n  File "a.py", line 1, in f\n    connect("{jwt}")\nValueError: nope\n'
    out = R.redact_obj({"error": {"stack": stack}})
    assert jwt not in out["error"]["stack"]
    assert "ValueError: nope" in out["error"]["stack"]
