/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FilesRouteImport } from './routes/files'
import { Route as AiVivaRouteImport } from './routes/ai-viva'
import { Route as AiPresentationRouteImport } from './routes/ai-presentation'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvancedIndexRouteImport } from './routes/advanced/index'
import { Route as TemplatesSlugRouteImport } from './routes/templates.$slug'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as AiVivaNewRouteImport } from './routes/ai-viva.new'
import { Route as AdvancedWeaknessHeatmapRouteImport } from './routes/advanced/weakness-heatmap'
import { Route as AdvancedVivaTeamRouteImport } from './routes/advanced/viva-team'
import { Route as AdvancedVivaCodeAwareRouteImport } from './routes/advanced/viva-code-aware'
import { Route as AdvancedSentimentAnalysisRouteImport } from './routes/advanced/sentiment-analysis'
import { Route as AdvancedPresentationBridgeRouteImport } from './routes/advanced/presentation-bridge'
import { Route as AdvancedFacultySimRouteImport } from './routes/advanced/faculty-sim'
import { Route as AdvancedCollegePredictorRouteImport } from './routes/advanced/college-predictor'
import { Route as AiVivaSessionIdRouteImport } from './routes/ai-viva.session.$id'
import { Route as AiPresentationSessionIdRouteImport } from './routes/ai-presentation.session.$id'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVivaRoute = AiVivaRouteImport.update({
  id: '/ai-viva',
  path: '/ai-viva',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPresentationRoute = AiPresentationRouteImport.update({
  id: '/ai-presentation',
  path: '/ai-presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedIndexRoute = AdvancedIndexRouteImport.update({
  id: '/advanced/',
  path: '/advanced/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugRoute = TemplatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TemplatesRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const AiVivaNewRoute = AiVivaNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AiVivaRoute,
} as any)
const AdvancedWeaknessHeatmapRoute = AdvancedWeaknessHeatmapRouteImport.update({
  id: '/advanced/weakness-heatmap',
  path: '/advanced/weakness-heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedVivaTeamRoute = AdvancedVivaTeamRouteImport.update({
  id: '/advanced/viva-team',
  path: '/advanced/viva-team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedVivaCodeAwareRoute = AdvancedVivaCodeAwareRouteImport.update({
  id: '/advanced/viva-code-aware',
  path: '/advanced/viva-code-aware',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedSentimentAnalysisRoute =
  AdvancedSentimentAnalysisRouteImport.update({
    id: '/advanced/sentiment-analysis',
    path: '/advanced/sentiment-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdvancedPresentationBridgeRoute =
  AdvancedPresentationBridgeRouteImport.update({
    id: '/advanced/presentation-bridge',
    path: '/advanced/presentation-bridge',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdvancedFacultySimRoute = AdvancedFacultySimRouteImport.update({
  id: '/advanced/faculty-sim',
  path: '/advanced/faculty-sim',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedCollegePredictorRoute =
  AdvancedCollegePredictorRouteImport.update({
    id: '/advanced/college-predictor',
    path: '/advanced/college-predictor',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVivaSessionIdRoute = AiVivaSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AiVivaRoute,
} as any)
const AiPresentationSessionIdRoute = AiPresentationSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AiPresentationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-presentation': typeof AiPresentationRouteWithChildren
  '/ai-viva': typeof AiVivaRouteWithChildren
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/signup': typeof SignupRoute
  '/teams': typeof TeamsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/advanced/college-predictor': typeof AdvancedCollegePredictorRoute
  '/advanced/faculty-sim': typeof AdvancedFacultySimRoute
  '/advanced/presentation-bridge': typeof AdvancedPresentationBridgeRoute
  '/advanced/sentiment-analysis': typeof AdvancedSentimentAnalysisRoute
  '/advanced/viva-code-aware': typeof AdvancedVivaCodeAwareRoute
  '/advanced/viva-team': typeof AdvancedVivaTeamRoute
  '/advanced/weakness-heatmap': typeof AdvancedWeaknessHeatmapRoute
  '/ai-viva/new': typeof AiVivaNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/advanced/': typeof AdvancedIndexRoute
  '/ai-presentation/session/$id': typeof AiPresentationSessionIdRoute
  '/ai-viva/session/$id': typeof AiVivaSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-presentation': typeof AiPresentationRouteWithChildren
  '/ai-viva': typeof AiVivaRouteWithChildren
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/signup': typeof SignupRoute
  '/teams': typeof TeamsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/advanced/college-predictor': typeof AdvancedCollegePredictorRoute
  '/advanced/faculty-sim': typeof AdvancedFacultySimRoute
  '/advanced/presentation-bridge': typeof AdvancedPresentationBridgeRoute
  '/advanced/sentiment-analysis': typeof AdvancedSentimentAnalysisRoute
  '/advanced/viva-code-aware': typeof AdvancedVivaCodeAwareRoute
  '/advanced/viva-team': typeof AdvancedVivaTeamRoute
  '/advanced/weakness-heatmap': typeof AdvancedWeaknessHeatmapRoute
  '/ai-viva/new': typeof AiVivaNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/advanced': typeof AdvancedIndexRoute
  '/ai-presentation/session/$id': typeof AiPresentationSessionIdRoute
  '/ai-viva/session/$id': typeof AiVivaSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/ai-presentation': typeof AiPresentationRouteWithChildren
  '/ai-viva': typeof AiVivaRouteWithChildren
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/signup': typeof SignupRoute
  '/teams': typeof TeamsRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/advanced/college-predictor': typeof AdvancedCollegePredictorRoute
  '/advanced/faculty-sim': typeof AdvancedFacultySimRoute
  '/advanced/presentation-bridge': typeof AdvancedPresentationBridgeRoute
  '/advanced/sentiment-analysis': typeof AdvancedSentimentAnalysisRoute
  '/advanced/viva-code-aware': typeof AdvancedVivaCodeAwareRoute
  '/advanced/viva-team': typeof AdvancedVivaTeamRoute
  '/advanced/weakness-heatmap': typeof AdvancedWeaknessHeatmapRoute
  '/ai-viva/new': typeof AiVivaNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/advanced/': typeof AdvancedIndexRoute
  '/ai-presentation/session/$id': typeof AiPresentationSessionIdRoute
  '/ai-viva/session/$id': typeof AiVivaSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/ai-presentation'
    | '/ai-viva'
    | '/files'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/projects'
    | '/signup'
    | '/teams'
    | '/templates'
    | '/advanced/college-predictor'
    | '/advanced/faculty-sim'
    | '/advanced/presentation-bridge'
    | '/advanced/sentiment-analysis'
    | '/advanced/viva-code-aware'
    | '/advanced/viva-team'
    | '/advanced/weakness-heatmap'
    | '/ai-viva/new'
    | '/projects/$id'
    | '/projects/new'
    | '/templates/$slug'
    | '/advanced/'
    | '/ai-presentation/session/$id'
    | '/ai-viva/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/ai-presentation'
    | '/ai-viva'
    | '/files'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/projects'
    | '/signup'
    | '/teams'
    | '/templates'
    | '/advanced/college-predictor'
    | '/advanced/faculty-sim'
    | '/advanced/presentation-bridge'
    | '/advanced/sentiment-analysis'
    | '/advanced/viva-code-aware'
    | '/advanced/viva-team'
    | '/advanced/weakness-heatmap'
    | '/ai-viva/new'
    | '/projects/$id'
    | '/projects/new'
    | '/templates/$slug'
    | '/advanced'
    | '/ai-presentation/session/$id'
    | '/ai-viva/session/$id'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/ai-presentation'
    | '/ai-viva'
    | '/files'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/projects'
    | '/signup'
    | '/teams'
    | '/templates'
    | '/advanced/college-predictor'
    | '/advanced/faculty-sim'
    | '/advanced/presentation-bridge'
    | '/advanced/sentiment-analysis'
    | '/advanced/viva-code-aware'
    | '/advanced/viva-team'
    | '/advanced/weakness-heatmap'
    | '/ai-viva/new'
    | '/projects/$id'
    | '/projects/new'
    | '/templates/$slug'
    | '/advanced/'
    | '/ai-presentation/session/$id'
    | '/ai-viva/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AiPresentationRoute: typeof AiPresentationRouteWithChildren
  AiVivaRoute: typeof AiVivaRouteWithChildren
  FilesRoute: typeof FilesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SignupRoute: typeof SignupRoute
  TeamsRoute: typeof TeamsRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  AdvancedCollegePredictorRoute: typeof AdvancedCollegePredictorRoute
  AdvancedFacultySimRoute: typeof AdvancedFacultySimRoute
  AdvancedPresentationBridgeRoute: typeof AdvancedPresentationBridgeRoute
  AdvancedSentimentAnalysisRoute: typeof AdvancedSentimentAnalysisRoute
  AdvancedVivaCodeAwareRoute: typeof AdvancedVivaCodeAwareRoute
  AdvancedVivaTeamRoute: typeof AdvancedVivaTeamRoute
  AdvancedWeaknessHeatmapRoute: typeof AdvancedWeaknessHeatmapRoute
  AdvancedIndexRoute: typeof AdvancedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-viva': {
      id: '/ai-viva'
      path: '/ai-viva'
      fullPath: '/ai-viva'
      preLoaderRoute: typeof AiVivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-presentation': {
      id: '/ai-presentation'
      path: '/ai-presentation'
      fullPath: '/ai-presentation'
      preLoaderRoute: typeof AiPresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/': {
      id: '/advanced/'
      path: '/advanced'
      fullPath: '/advanced/'
      preLoaderRoute: typeof AdvancedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug': {
      id: '/templates/$slug'
      path: '/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof TemplatesSlugRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/ai-viva/new': {
      id: '/ai-viva/new'
      path: '/new'
      fullPath: '/ai-viva/new'
      preLoaderRoute: typeof AiVivaNewRouteImport
      parentRoute: typeof AiVivaRoute
    }
    '/advanced/weakness-heatmap': {
      id: '/advanced/weakness-heatmap'
      path: '/advanced/weakness-heatmap'
      fullPath: '/advanced/weakness-heatmap'
      preLoaderRoute: typeof AdvancedWeaknessHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/viva-team': {
      id: '/advanced/viva-team'
      path: '/advanced/viva-team'
      fullPath: '/advanced/viva-team'
      preLoaderRoute: typeof AdvancedVivaTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/viva-code-aware': {
      id: '/advanced/viva-code-aware'
      path: '/advanced/viva-code-aware'
      fullPath: '/advanced/viva-code-aware'
      preLoaderRoute: typeof AdvancedVivaCodeAwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/sentiment-analysis': {
      id: '/advanced/sentiment-analysis'
      path: '/advanced/sentiment-analysis'
      fullPath: '/advanced/sentiment-analysis'
      preLoaderRoute: typeof AdvancedSentimentAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/presentation-bridge': {
      id: '/advanced/presentation-bridge'
      path: '/advanced/presentation-bridge'
      fullPath: '/advanced/presentation-bridge'
      preLoaderRoute: typeof AdvancedPresentationBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/faculty-sim': {
      id: '/advanced/faculty-sim'
      path: '/advanced/faculty-sim'
      fullPath: '/advanced/faculty-sim'
      preLoaderRoute: typeof AdvancedFacultySimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/college-predictor': {
      id: '/advanced/college-predictor'
      path: '/advanced/college-predictor'
      fullPath: '/advanced/college-predictor'
      preLoaderRoute: typeof AdvancedCollegePredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-viva/session/$id': {
      id: '/ai-viva/session/$id'
      path: '/session/$id'
      fullPath: '/ai-viva/session/$id'
      preLoaderRoute: typeof AiVivaSessionIdRouteImport
      parentRoute: typeof AiVivaRoute
    }
    '/ai-presentation/session/$id': {
      id: '/ai-presentation/session/$id'
      path: '/session/$id'
      fullPath: '/ai-presentation/session/$id'
      preLoaderRoute: typeof AiPresentationSessionIdRouteImport
      parentRoute: typeof AiPresentationRoute
    }
  }
}

interface AiPresentationRouteChildren {
  AiPresentationSessionIdRoute: typeof AiPresentationSessionIdRoute
}

const AiPresentationRouteChildren: AiPresentationRouteChildren = {
  AiPresentationSessionIdRoute: AiPresentationSessionIdRoute,
}

const AiPresentationRouteWithChildren = AiPresentationRoute._addFileChildren(
  AiPresentationRouteChildren,
)

interface AiVivaRouteChildren {
  AiVivaNewRoute: typeof AiVivaNewRoute
  AiVivaSessionIdRoute: typeof AiVivaSessionIdRoute
}

const AiVivaRouteChildren: AiVivaRouteChildren = {
  AiVivaNewRoute: AiVivaNewRoute,
  AiVivaSessionIdRoute: AiVivaSessionIdRoute,
}

const AiVivaRouteWithChildren =
  AiVivaRoute._addFileChildren(AiVivaRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesSlugRoute: typeof TemplatesSlugRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesSlugRoute: TemplatesSlugRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AiPresentationRoute: AiPresentationRouteWithChildren,
  AiVivaRoute: AiVivaRouteWithChildren,
  FilesRoute: FilesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SignupRoute: SignupRoute,
  TeamsRoute: TeamsRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  AdvancedCollegePredictorRoute: AdvancedCollegePredictorRoute,
  AdvancedFacultySimRoute: AdvancedFacultySimRoute,
  AdvancedPresentationBridgeRoute: AdvancedPresentationBridgeRoute,
  AdvancedSentimentAnalysisRoute: AdvancedSentimentAnalysisRoute,
  AdvancedVivaCodeAwareRoute: AdvancedVivaCodeAwareRoute,
  AdvancedVivaTeamRoute: AdvancedVivaTeamRoute,
  AdvancedWeaknessHeatmapRoute: AdvancedWeaknessHeatmapRoute,
  AdvancedIndexRoute: AdvancedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
