/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PitchDrillRouteImport } from './routes/pitch-drill'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FilesRouteImport } from './routes/files'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TeamsIndexRouteImport } from './routes/teams/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AiVivaIndexRouteImport } from './routes/ai-viva/index'
import { Route as AiPresentationIndexRouteImport } from './routes/ai-presentation/index'
import { Route as AdvancedIndexRouteImport } from './routes/advanced/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TemplatesSlugRouteImport } from './routes/templates/$slug'
import { Route as TeamsIdRouteImport } from './routes/teams/$id'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as AiVivaNewRouteImport } from './routes/ai-viva/new'
import { Route as AdvancedWeaknessHeatmapRouteImport } from './routes/advanced/weakness-heatmap'
import { Route as AdvancedVivaTeamRouteImport } from './routes/advanced/viva-team'
import { Route as AdvancedVivaCodeAwareRouteImport } from './routes/advanced/viva-code-aware'
import { Route as AdvancedSentimentAnalysisRouteImport } from './routes/advanced/sentiment-analysis'
import { Route as AiVivaSessionIdRouteImport } from './routes/ai-viva/session.$id'
import { Route as AiPresentationSessionIdRouteImport } from './routes/ai-presentation/session.$id'
import { Route as AdvancedVivaTeamJoinJoinCodeRouteImport } from './routes/advanced/viva-team_.join.$joinCode'
import { Route as AdvancedVivaCodeAwareSessionIdRouteImport } from './routes/advanced/viva-code-aware_.session.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchDrillRoute = PitchDrillRouteImport.update({
  id: '/pitch-drill',
  path: '/pitch-drill',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVivaIndexRoute = AiVivaIndexRouteImport.update({
  id: '/ai-viva/',
  path: '/ai-viva/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPresentationIndexRoute = AiPresentationIndexRouteImport.update({
  id: '/ai-presentation/',
  path: '/ai-presentation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedIndexRoute = AdvancedIndexRouteImport.update({
  id: '/advanced/',
  path: '/advanced/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugRoute = TemplatesSlugRouteImport.update({
  id: '/templates/$slug',
  path: '/templates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVivaNewRoute = AiVivaNewRouteImport.update({
  id: '/ai-viva/new',
  path: '/ai-viva/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedWeaknessHeatmapRoute = AdvancedWeaknessHeatmapRouteImport.update({
  id: '/advanced/weakness-heatmap',
  path: '/advanced/weakness-heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedVivaTeamRoute = AdvancedVivaTeamRouteImport.update({
  id: '/advanced/viva-team',
  path: '/advanced/viva-team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedVivaCodeAwareRoute = AdvancedVivaCodeAwareRouteImport.update({
  id: '/advanced/viva-code-aware',
  path: '/advanced/viva-code-aware',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedSentimentAnalysisRoute =
  AdvancedSentimentAnalysisRouteImport.update({
    id: '/advanced/sentiment-analysis',
    path: '/advanced/sentiment-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiVivaSessionIdRoute = AiVivaSessionIdRouteImport.update({
  id: '/ai-viva/session/$id',
  path: '/ai-viva/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AiPresentationSessionIdRoute = AiPresentationSessionIdRouteImport.update({
  id: '/ai-presentation/session/$id',
  path: '/ai-presentation/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedVivaTeamJoinJoinCodeRoute =
  AdvancedVivaTeamJoinJoinCodeRouteImport.update({
    id: '/advanced/viva-team_/join/$joinCode',
    path: '/advanced/viva-team/join/$joinCode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdvancedVivaCodeAwareSessionIdRoute =
  AdvancedVivaCodeAwareSessionIdRouteImport.update({
    id: '/advanced/viva-code-aware_/session/$id',
    path: '/advanced/viva-code-aware/session/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pitch-drill': typeof PitchDrillRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/readiness': typeof ReadinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/advanced/sentiment-analysis': typeof AdvancedSentimentAnalysisRoute
  '/advanced/viva-code-aware': typeof AdvancedVivaCodeAwareRoute
  '/advanced/viva-team': typeof AdvancedVivaTeamRoute
  '/advanced/weakness-heatmap': typeof AdvancedWeaknessHeatmapRoute
  '/ai-viva/new': typeof AiVivaNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/teams/$id': typeof TeamsIdRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/advanced/': typeof AdvancedIndexRoute
  '/ai-presentation/': typeof AiPresentationIndexRoute
  '/ai-viva/': typeof AiVivaIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/ai-presentation/session/$id': typeof AiPresentationSessionIdRoute
  '/ai-viva/session/$id': typeof AiVivaSessionIdRoute
  '/advanced/viva-code-aware/session/$id': typeof AdvancedVivaCodeAwareSessionIdRoute
  '/advanced/viva-team/join/$joinCode': typeof AdvancedVivaTeamJoinJoinCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pitch-drill': typeof PitchDrillRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/readiness': typeof ReadinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/advanced/sentiment-analysis': typeof AdvancedSentimentAnalysisRoute
  '/advanced/viva-code-aware': typeof AdvancedVivaCodeAwareRoute
  '/advanced/viva-team': typeof AdvancedVivaTeamRoute
  '/advanced/weakness-heatmap': typeof AdvancedWeaknessHeatmapRoute
  '/ai-viva/new': typeof AiVivaNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/teams/$id': typeof TeamsIdRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/advanced': typeof AdvancedIndexRoute
  '/ai-presentation': typeof AiPresentationIndexRoute
  '/ai-viva': typeof AiVivaIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/ai-presentation/session/$id': typeof AiPresentationSessionIdRoute
  '/ai-viva/session/$id': typeof AiVivaSessionIdRoute
  '/advanced/viva-code-aware/session/$id': typeof AdvancedVivaCodeAwareSessionIdRoute
  '/advanced/viva-team/join/$joinCode': typeof AdvancedVivaTeamJoinJoinCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/files': typeof FilesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pitch-drill': typeof PitchDrillRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/readiness': typeof ReadinessRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/advanced/sentiment-analysis': typeof AdvancedSentimentAnalysisRoute
  '/advanced/viva-code-aware': typeof AdvancedVivaCodeAwareRoute
  '/advanced/viva-team': typeof AdvancedVivaTeamRoute
  '/advanced/weakness-heatmap': typeof AdvancedWeaknessHeatmapRoute
  '/ai-viva/new': typeof AiVivaNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/teams/$id': typeof TeamsIdRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/advanced/': typeof AdvancedIndexRoute
  '/ai-presentation/': typeof AiPresentationIndexRoute
  '/ai-viva/': typeof AiVivaIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/ai-presentation/session/$id': typeof AiPresentationSessionIdRoute
  '/ai-viva/session/$id': typeof AiVivaSessionIdRoute
  '/advanced/viva-code-aware_/session/$id': typeof AdvancedVivaCodeAwareSessionIdRoute
  '/advanced/viva-team_/join/$joinCode': typeof AdvancedVivaTeamJoinJoinCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/files'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/pitch-drill'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/readiness'
    | '/reset-password'
    | '/signup'
    | '/advanced/sentiment-analysis'
    | '/advanced/viva-code-aware'
    | '/advanced/viva-team'
    | '/advanced/weakness-heatmap'
    | '/ai-viva/new'
    | '/projects/$id'
    | '/projects/new'
    | '/teams/$id'
    | '/templates/$slug'
    | '/admin/'
    | '/advanced/'
    | '/ai-presentation/'
    | '/ai-viva/'
    | '/projects/'
    | '/teams/'
    | '/templates/'
    | '/ai-presentation/session/$id'
    | '/ai-viva/session/$id'
    | '/advanced/viva-code-aware/session/$id'
    | '/advanced/viva-team/join/$joinCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/files'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/pitch-drill'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/readiness'
    | '/reset-password'
    | '/signup'
    | '/advanced/sentiment-analysis'
    | '/advanced/viva-code-aware'
    | '/advanced/viva-team'
    | '/advanced/weakness-heatmap'
    | '/ai-viva/new'
    | '/projects/$id'
    | '/projects/new'
    | '/teams/$id'
    | '/templates/$slug'
    | '/admin'
    | '/advanced'
    | '/ai-presentation'
    | '/ai-viva'
    | '/projects'
    | '/teams'
    | '/templates'
    | '/ai-presentation/session/$id'
    | '/ai-viva/session/$id'
    | '/advanced/viva-code-aware/session/$id'
    | '/advanced/viva-team/join/$joinCode'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/files'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/onboarding'
    | '/pitch-drill'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/readiness'
    | '/reset-password'
    | '/signup'
    | '/advanced/sentiment-analysis'
    | '/advanced/viva-code-aware'
    | '/advanced/viva-team'
    | '/advanced/weakness-heatmap'
    | '/ai-viva/new'
    | '/projects/$id'
    | '/projects/new'
    | '/teams/$id'
    | '/templates/$slug'
    | '/admin/'
    | '/advanced/'
    | '/ai-presentation/'
    | '/ai-viva/'
    | '/projects/'
    | '/teams/'
    | '/templates/'
    | '/ai-presentation/session/$id'
    | '/ai-viva/session/$id'
    | '/advanced/viva-code-aware_/session/$id'
    | '/advanced/viva-team_/join/$joinCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  FilesRoute: typeof FilesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PitchDrillRoute: typeof PitchDrillRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  ReadinessRoute: typeof ReadinessRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdvancedSentimentAnalysisRoute: typeof AdvancedSentimentAnalysisRoute
  AdvancedVivaCodeAwareRoute: typeof AdvancedVivaCodeAwareRoute
  AdvancedVivaTeamRoute: typeof AdvancedVivaTeamRoute
  AdvancedWeaknessHeatmapRoute: typeof AdvancedWeaknessHeatmapRoute
  AiVivaNewRoute: typeof AiVivaNewRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  TeamsIdRoute: typeof TeamsIdRoute
  TemplatesSlugRoute: typeof TemplatesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdvancedIndexRoute: typeof AdvancedIndexRoute
  AiPresentationIndexRoute: typeof AiPresentationIndexRoute
  AiVivaIndexRoute: typeof AiVivaIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  AiPresentationSessionIdRoute: typeof AiPresentationSessionIdRoute
  AiVivaSessionIdRoute: typeof AiVivaSessionIdRoute
  AdvancedVivaCodeAwareSessionIdRoute: typeof AdvancedVivaCodeAwareSessionIdRoute
  AdvancedVivaTeamJoinJoinCodeRoute: typeof AdvancedVivaTeamJoinJoinCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch-drill': {
      id: '/pitch-drill'
      path: '/pitch-drill'
      fullPath: '/pitch-drill'
      preLoaderRoute: typeof PitchDrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-viva/': {
      id: '/ai-viva/'
      path: '/ai-viva'
      fullPath: '/ai-viva/'
      preLoaderRoute: typeof AiVivaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-presentation/': {
      id: '/ai-presentation/'
      path: '/ai-presentation'
      fullPath: '/ai-presentation/'
      preLoaderRoute: typeof AiPresentationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/': {
      id: '/advanced/'
      path: '/advanced'
      fullPath: '/advanced/'
      preLoaderRoute: typeof AdvancedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug': {
      id: '/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof TemplatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/teams/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-viva/new': {
      id: '/ai-viva/new'
      path: '/ai-viva/new'
      fullPath: '/ai-viva/new'
      preLoaderRoute: typeof AiVivaNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/weakness-heatmap': {
      id: '/advanced/weakness-heatmap'
      path: '/advanced/weakness-heatmap'
      fullPath: '/advanced/weakness-heatmap'
      preLoaderRoute: typeof AdvancedWeaknessHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/viva-team': {
      id: '/advanced/viva-team'
      path: '/advanced/viva-team'
      fullPath: '/advanced/viva-team'
      preLoaderRoute: typeof AdvancedVivaTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/viva-code-aware': {
      id: '/advanced/viva-code-aware'
      path: '/advanced/viva-code-aware'
      fullPath: '/advanced/viva-code-aware'
      preLoaderRoute: typeof AdvancedVivaCodeAwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/sentiment-analysis': {
      id: '/advanced/sentiment-analysis'
      path: '/advanced/sentiment-analysis'
      fullPath: '/advanced/sentiment-analysis'
      preLoaderRoute: typeof AdvancedSentimentAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-viva/session/$id': {
      id: '/ai-viva/session/$id'
      path: '/ai-viva/session/$id'
      fullPath: '/ai-viva/session/$id'
      preLoaderRoute: typeof AiVivaSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-presentation/session/$id': {
      id: '/ai-presentation/session/$id'
      path: '/ai-presentation/session/$id'
      fullPath: '/ai-presentation/session/$id'
      preLoaderRoute: typeof AiPresentationSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/viva-team_/join/$joinCode': {
      id: '/advanced/viva-team_/join/$joinCode'
      path: '/advanced/viva-team/join/$joinCode'
      fullPath: '/advanced/viva-team/join/$joinCode'
      preLoaderRoute: typeof AdvancedVivaTeamJoinJoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced/viva-code-aware_/session/$id': {
      id: '/advanced/viva-code-aware_/session/$id'
      path: '/advanced/viva-code-aware/session/$id'
      fullPath: '/advanced/viva-code-aware/session/$id'
      preLoaderRoute: typeof AdvancedVivaCodeAwareSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  FilesRoute: FilesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PitchDrillRoute: PitchDrillRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  ReadinessRoute: ReadinessRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdvancedSentimentAnalysisRoute: AdvancedSentimentAnalysisRoute,
  AdvancedVivaCodeAwareRoute: AdvancedVivaCodeAwareRoute,
  AdvancedVivaTeamRoute: AdvancedVivaTeamRoute,
  AdvancedWeaknessHeatmapRoute: AdvancedWeaknessHeatmapRoute,
  AiVivaNewRoute: AiVivaNewRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  TeamsIdRoute: TeamsIdRoute,
  TemplatesSlugRoute: TemplatesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdvancedIndexRoute: AdvancedIndexRoute,
  AiPresentationIndexRoute: AiPresentationIndexRoute,
  AiVivaIndexRoute: AiVivaIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  AiPresentationSessionIdRoute: AiPresentationSessionIdRoute,
  AiVivaSessionIdRoute: AiVivaSessionIdRoute,
  AdvancedVivaCodeAwareSessionIdRoute: AdvancedVivaCodeAwareSessionIdRoute,
  AdvancedVivaTeamJoinJoinCodeRoute: AdvancedVivaTeamJoinJoinCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
